"""add passowrd and user name to admin model

Revision ID: 5cbd9a9a3c60
Revises: 9ed42236ca6a
Create Date: 2025-10-17 11:22:43.740146

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5cbd9a9a3c60"
down_revision: Union[str, Sequence[str], None] = "9ed42236ca6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("username", sa.String(length=64), nullable=True))
    op.add_column("admins", sa.Column("password", sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, "admins", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "admins", type_="unique")
    op.drop_column("admins", "password")
    op.drop_column("admins", "username")
    # ### end Alembic commands ###
