"""refactoring

Revision ID: 0ebd616af2e4
Revises: 037fc82ac6ec
Create Date: 2025-10-18 20:32:59.476008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebd616af2e4'
down_revision: Union[str, Sequence[str], None] = '037fc82ac6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'is_active')
    # ### end Alembic commands ###
