"""added group_id to lesson

Revision ID: b865f27532e3
Revises: 9e6093e2c8a4
Create Date: 2025-10-18 19:11:43.925427

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b865f27532e3"
down_revision: Union[str, Sequence[str], None] = "9e6093e2c8a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lessons", sa.Column("course_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "lessons", "courses", ["course_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lessons", type_="foreignkey")
    op.drop_column("lessons", "course_id")
    # ### end Alembic commands ###
