"""refactoring

Revision ID: 037fc82ac6ec
Revises: b865f27532e3
Create Date: 2025-10-18 20:06:56.579465

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "037fc82ac6ec"
down_revision: Union[str, Sequence[str], None] = "b865f27532e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teacher_student")
    op.drop_table("course_users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_users",
        sa.Column("course_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "joined_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("course_users_course_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["telegram_users.id"],
            name=op.f("course_users_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("course_id", "user_id", name=op.f("course_users_pkey")),
    )
    op.create_table(
        "teacher_student",
        sa.Column("teacher_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("student_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["telegram_users.id"],
            name=op.f("teacher_student_student_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("teacher_student_teacher_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "teacher_id", "student_id", name=op.f("teacher_student_pkey")
        ),
    )
    # ### end Alembic commands ###
