"""added task_progres

Revision ID: 3482d98178ab
Revises: 4b93dee4ac4b
Create Date: 2025-10-19 19:58:46.096295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3482d98178ab"
down_revision: Union[str, Sequence[str], None] = "4b93dee4ac4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task_progress", sa.Column("group_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "task_progress", "groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task_progress", type_="foreignkey")
    op.drop_column("task_progress", "group_id")
    # ### end Alembic commands ###
