"""added link_id to group_user model

Revision ID: a5acfabeb5a3
Revises: 0ebd616af2e4
Create Date: 2025-10-19 17:37:47.234965

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5acfabeb5a3"
down_revision: Union[str, Sequence[str], None] = "0ebd616af2e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group_users", sa.Column("link_event_id", sa.Integer(), nullable=True)
    )
    op.add_column("group_users", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.create_foreign_key(
        None,
        "group_users",
        "link_events",
        ["link_event_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group_users", type_="foreignkey")
    op.drop_column("group_users", "is_active")
    op.drop_column("group_users", "link_event_id")
    # ### end Alembic commands ###
